# Copyright 2026 AtomicStrata
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.
"""A `console` fence that shows a block's output shows what the block prints.

`test_runnable_blocks.py` runs every Python block and deliberately does not compare its output
to the fence beside it. So `reference/catalog.md` printed "memrank ships 11 system(s) and 5
evaluation(s)" for a release in which `memrank.catalog()` printed six, with SQuAD as its first
evaluation row: the fence had been regenerated by hand once and nothing held it to the code
afterwards. The page whose whole purpose is "what ships" disagreed with the call it documents.

A fence opts in by declaring what it is, on the nearest non-blank line above it::

    <!-- output: exact -->

and it is then compared, whole and line for line, with the stdout of the nearest Python block
above it on the same page. `latency-masked` does the same with the value of every `latency.*`
line blanked, for the one kind of output that is memrank's own clock and legitimately differs
on every run -- nothing here asserts on a duration.

Opting in is by marker rather than by default because a `console` fence is not always a block's
output: some show one line of a refusal, some show a shell session. The floor below keeps the
markers from all quietly disappearing.
"""
from __future__ import annotations

import re
from dataclasses import dataclass

import pytest

from tests.repo.prose import ROOT
from tests.repo.test_runnable_blocks import (
    BLOCKS,
    DOCUMENTS,
    FENCE,
    Block,
    execute,
)

MARKER = re.compile(r"^\s*<!--\s*output:\s*(exact|latency-masked)\s*-->\s*$")
LATENCY_VALUE = re.compile(r"^(\s*latency\.\S+\s+)\S+")


@dataclass(frozen=True)
class Fence:
    """One `console` fence that declared itself a block's output."""

    path: str
    line: int
    body: str
    mode: str

    @property
    def id(self) -> str:
        return f"{self.path}:{self.line}"


def _marker(lines: list[str], index: int) -> str | None:
    for candidate in reversed(lines[:index]):
        if candidate.strip():
            found = MARKER.match(candidate)
            return found.group(1) if found else None
    return None


def fences_in(path: str, text: str) -> list[Fence]:
    """Every marked `console` fence in one document."""
    lines, found = text.splitlines(), []
    closing: re.Match[str] | None = None
    opened = 0
    body: list[str] = []
    for index, line in enumerate(lines):
        fence = FENCE.match(line)
        if closing is None:
            if fence:
                closing, opened, body = fence, index, []
            continue
        if fence and fence.group(1)[0] == closing.group(1)[0] \
                and len(fence.group(1)) >= len(closing.group(1)):
            mode = _marker(lines, opened)
            if closing.group(2) == "console" and mode:
                found.append(Fence(path, opened + 1, "\n".join(body), mode))
            closing = None
        else:
            body.append(line)
    return found


def _source_of(fence: Fence) -> Block | None:
    """The nearest Python block above the fence on its own page."""
    above = [b for b in BLOCKS if b.path == fence.path and b.line < fence.line]
    return above[-1] if above else None


def _shown(text: str, mode: str) -> str:
    lines = text.rstrip().splitlines()
    if mode == "latency-masked":
        lines = [LATENCY_VALUE.sub(r"\1#", line) for line in lines]
    return "\n".join(line.rstrip() for line in lines)


FENCES = [f for path in DOCUMENTS
          for f in fences_in(path, (ROOT / path).read_text(encoding="utf-8"))]


@pytest.mark.parametrize("fence", FENCES, ids=lambda f: f.id)
def test_the_fence_is_what_the_block_prints(fence: Fence):
    source = _source_of(fence)
    assert source is not None, f"{fence.id} declares output but has no Python block above it"
    assert source.reason is None, (
        f"{fence.id} shows the output of {source.id}, which declares it is not run")
    completed = execute(source)
    assert completed.returncode == 0, f"{source.id} exits {completed.returncode}"
    assert _shown(completed.stdout, fence.mode) == _shown(fence.body, fence.mode), (
        f"{fence.id} does not show what {source.id} prints. It prints:\n{completed.stdout}")


def test_the_pages_that_show_output_still_declare_it():
    """The markers' own guard: removing one would exempt its fence in silence."""
    marked = {f.path for f in FENCES}
    for must_cover in ("docs/reference/catalog.md", "docs/reference/result.md",
                       "docs/measures.md"):
        assert must_cover in marked, f"{must_cover} no longer declares its output fence"


def test_the_mask_blanks_only_the_clock():
    shown = _shown("  latency.retrieve.p50   0.752  decided by memrank\n  squad-score 0.969",
                   "latency-masked")
    assert shown == "  latency.retrieve.p50   #  decided by memrank\n  squad-score 0.969"
